/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Material-inspired Acorn design system colors
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fcf2eb',
        'surface-container': '#f6ece6',
        'surface-container-high': '#f0e6e0',
        'surface-container-highest': '#eae1da',
        'surface': '#fff8f5',
        'surface-dim': '#e2d8d2',
        'surface-bright': '#fff8f5',
        'surface-variant': '#eae1da',
        'surface-tint': '#904d00',
        'on-surface': '#1f1b17',
        'on-surface-variant': '#554336',
        'inverse-surface': '#342f2b',
        'inverse-on-surface': '#f9efe8',
        'background': '#fff8f5',
        'on-background': '#1f1b17',
        'outline': '#887364',
        'outline-variant': '#dbc2b0',

        'primary': '#8d4b00',
        'on-primary': '#ffffff',
        'primary-container': '#b15f00',
        'on-primary-container': '#fffbff',
        'primary-fixed': '#ffdcc3',
        'primary-fixed-dim': '#ffb77d',
        'on-primary-fixed': '#2f1500',
        'on-primary-fixed-variant': '#6e3900',
        'inverse-primary': '#ffb77d',

        'secondary': '#006c49',
        'on-secondary': '#ffffff',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',

        'tertiary': '#4648d4',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6063ee',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#e1e0ff',
        'tertiary-fixed-dim': '#c0c1ff',
        'on-tertiary-fixed': '#07006c',
        'on-tertiary-fixed-variant': '#2f2ebe',

        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        // Brand accents
        'acorn-amber': '#D97706',
        'acorn-amber-hover': '#B45309',
        'acorn-amber-subtle': '#FEF3C7',
        'acorn-amber-ghost': '#FFFBEB',
        'forest-spruce': '#10B981',
        'forest-spruce-subtle': '#ECFDF5',
        'forest-spruce-deep': '#047857',
        'deep-iris': '#6366F1',
        'deep-iris-subtle': '#EEF2FF',
        'deep-iris-deep': '#4338CA',
        'attention-rose': '#F43F5E',
        'attention-rose-subtle': '#FFF1F2',

        // Structural
        'canvas-base': '#FBFBFA',
        'text-primary-color': '#1C1917',
        'text-secondary-color': '#57534E',
        'text-tertiary-color': '#A8A29E',
        'hairline-border': '#F3F4F6',
        'default-divider': '#E7E5E4',
        'strong-border': '#D6D3D1',
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'sm': '0.25rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'margin': '1rem',
        'margin-desktop': '2rem',
        'gutter': '1rem',
        'gutter-desktop': '1.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans', 'Pretendard', '-apple-system', 'BlinkMacSystemFont', 'Apple SD Gothic Neo', 'sans-serif'],
        'body': ['Inter', 'Pretendard', '-apple-system', 'BlinkMacSystemFont', 'Apple SD Gothic Neo', 'sans-serif'],
        'code': ['Space Mono', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-xl-mobile': ['26px', { lineHeight: '34px', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '19px', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'code-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
      },
      boxShadow: {
        'tier-1': '0 1px 3px rgba(120, 113, 108, 0.06), 0 1px 2px rgba(120, 113, 108, 0.04)',
        'tier-2': '0 8px 20px -4px rgba(180, 83, 9, 0.08), 0 4px 6px -2px rgba(28, 25, 23, 0.03)',
        'tier-3': '0 16px 32px -8px rgba(28, 25, 23, 0.1), 0 4px 8px -2px rgba(28, 25, 23, 0.04)',
        'header': '0 1px 8px rgba(40, 30, 20, 0.05)',
        'sidebar': '1px 0 12px rgba(40, 30, 20, 0.03)',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
};
